In [1]:
# --- Imports ---
import pandas as pd
from IPython.display import display
import sys
import os

# Add root directory to path
sys.path.append(os.path.abspath(".."))

from scripts.util.getters import get_dataset_paths

In [2]:
# --- Config ---
ENHANCEMENTS = ["raw", "srl", "kga", "rbm", "srt"]

In [3]:
# --- Helper Function ---
def review_dataset(path: str, name: str):
    print(f"\nReviewing {name} — ({path})")

    try:
        df = pd.read_csv(path, sep="\t", header=None)
    except FileNotFoundError:
        print(f"File not found: {path}")
        return

    print("Loaded:", name)
    print("Shape:", df.shape)
    display(df.head(3))

    if df.shape[1] >= 2:
        print("Input Distribution:")
        print(df[0].value_counts().head(), "\n")

        print("Output Distribution:")
        print(df[1].value_counts().head(), "\n")

    if df.shape[1] == 3:
        print("Roles Distribution:")
        print(df[2].value_counts().head(), "\n")

In [4]:
paths = get_dataset_paths("raw")
for split in ["train", "dev", "test", "gen"]:
    review_dataset(paths[split], name=f"RAW - {split}")

Reviewing RAW - train — (/notebooks/meta-semantic-research/data/raw/train.tsv)
Loaded: RAW - train
Shape: (24155, 3)

,0,1,2
0,A rose was helped by a dog .,"rose ( x _ 1 ) AND help . theme ( x _ 3 , x _ ...",in_distribution
1,The sailor dusted a boy .,"* sailor ( x _ 1 ) ; dust . agent ( x _ 2 , x ...",in_distribution
2,Emma rolled a teacher .,"roll . agent ( x _ 1 , Emma ) AND roll . theme...",in_distribution

Input Distribution:
0
A rose was helped by a dog .                    1
The sandwich was called .                       1
A girl gave Liam the cracker beside a monk .    1
The bird crumpled a strawberry .                1
The raisin was given to Olivia .                1
Name: count, dtype: int64

Output Distribution:
1
rose ( x _ 1 ) AND help . theme ( x _ 3 , x _ 1 ) AND help . agent ( x _ 3 , x _ 6 ) AND dog ( x _ 6 )                                                                                                               1
* sandwich ( x _ 1 ) ; call . theme ( x _ 3 , x _ 1 )                                                                                                                                                                1
* cracker ( x _ 5 ) ; girl ( x _ 1 ) AND give . agent ( x _ 2 , x _ 1 ) AND give . recipient ( x _ 2 , Liam ) AND give . theme ( x _ 2 , x _ 5 ) AND cracker . nmod . beside ( x _ 5 , x _ 8 ) AND monk ( x _ 8 )    1
* bird ( x _ 1 ) ; crumple . agent ( x _ 2 , x _ 1 ) AND crumple . theme ( x _ 2 , x _ 4 ) AND strawberry ( x _ 4 )                                                                                                  1
* raisin ( x _ 1 ) ; give . theme ( x _ 3 , x _ 1 ) AND give . recipient ( x _ 3 , Olivia )                                                                                                                          1
Name: count, dtype: int64

Roles Distribution:
2
in_distribution                 24000
primitive                         143
exposure_example_unacc_subj         1
exposure_example_unacc              1
exposure_example_subj_common        1
Name: count, dtype: int64


Reviewing RAW - dev — (/notebooks/meta-semantic-research/data/raw/dev.tsv)
Loaded: RAW - dev
Shape: (3000, 3)

,0,1,2
0,Liam hoped that a box was burned by a girl .,"hope . agent ( x _ 1 , Liam ) AND hope . ccomp...",in_distribution
1,The donkey lended the cookie to a mother .,* donkey ( x _ 1 ) ; * cookie ( x _ 4 ) ; lend...,in_distribution
2,A melon was given to a girl by the guard .,* guard ( x _ 9 ) ; melon ( x _ 1 ) AND give ....,in_distribution

Input Distribution:
0
Liam hoped that a box was burned by a girl .                  1
Isabella liked that James painted a dog .                     1
A chicken drew .                                              1
William packed a boy .                                        1
Emma hoped that Noah liked that a crayon was appreciated .    1
Name: count, dtype: int64

Output Distribution:
1
hope . agent ( x _ 1 , Liam ) AND hope . ccomp ( x _ 1 , x _ 6 ) AND box ( x _ 4 ) AND burn . theme ( x _ 6 , x _ 4 ) AND burn . agent ( x _ 6 , x _ 9 ) AND girl ( x _ 9 )                            1
like . agent ( x _ 1 , Isabella ) AND like . ccomp ( x _ 1 , x _ 4 ) AND paint . agent ( x _ 4 , James ) AND paint . theme ( x _ 4 , x _ 6 ) AND dog ( x _ 6 )                                         1
chicken ( x _ 1 ) AND draw . agent ( x _ 2 , x _ 1 )                                                                                                                                                   1
pack . agent ( x _ 1 , William ) AND pack . theme ( x _ 1 , x _ 3 ) AND boy ( x _ 3 )                                                                                                                  1
hope . agent ( x _ 1 , Emma ) AND hope . ccomp ( x _ 1 , x _ 4 ) AND like . agent ( x _ 4 , Noah ) AND like . ccomp ( x _ 4 , x _ 9 ) AND crayon ( x _ 7 ) AND appreciate . theme ( x _ 9 , x _ 7 )    1
Name: count, dtype: int64

Roles Distribution:
2
in_distribution    3000
Name: count, dtype: int64


Reviewing RAW - test — (/notebooks/meta-semantic-research/data/raw/test.tsv)
Loaded: RAW - test
Shape: (3000, 3)

,0,1,2
0,Mila liked that the cake was offered to Emma .,"* cake ( x _ 4 ) ; like . agent ( x _ 1 , Mila...",in_distribution
1,A coach supported that the cake was snapped .,* cake ( x _ 5 ) ; coach ( x _ 1 ) AND support...,in_distribution
2,The moose wanted to read .,"* moose ( x _ 1 ) ; want . agent ( x _ 2 , x _...",in_distribution

Input Distribution:
0
Mila liked that the cake was offered to Emma .    1
Stella wanted to smirk .                          1
The book was liked .                              1
Emma promised a crayon on a paper to a girl .     1
The box was valued by Olivia .                    1
Name: count, dtype: int64

Output Distribution:
1
* cake ( x _ 4 ) ; like . agent ( x _ 1 , Mila ) AND like . ccomp ( x _ 1 , x _ 6 ) AND offer . theme ( x _ 6 , x _ 4 ) AND offer . recipient ( x _ 6 , Emma )                                                           1
want . agent ( x _ 1 , Stella ) AND want . xcomp ( x _ 1 , x _ 3 ) AND smirk . agent ( x _ 3 , Stella )                                                                                                                  1
* book ( x _ 1 ) ; like . theme ( x _ 3 , x _ 1 )                                                                                                                                                                        1
promise . agent ( x _ 1 , Emma ) AND promise . theme ( x _ 1 , x _ 3 ) AND promise . recipient ( x _ 1 , x _ 9 ) AND crayon ( x _ 3 ) AND crayon . nmod . on ( x _ 3 , x _ 6 ) AND paper ( x _ 6 ) AND girl ( x _ 9 )    1
* box ( x _ 1 ) ; value . theme ( x _ 3 , x _ 1 ) AND value . agent ( x _ 3 , Olivia )                                                                                                                                   1
Name: count, dtype: int64

Roles Distribution:
2
in_distribution    3000
Name: count, dtype: int64


Reviewing RAW - gen — (/notebooks/meta-semantic-research/data/raw/gen.tsv)
Loaded: RAW - gen
Shape: (21000, 3)

,0,1,2
0,Paula painted a cake in a closet .,"paint . agent ( x _ 1 , Paula ) AND paint . th...",prim_to_subj_proper
1,Zoe thought that a hippo cleaned .,"think . agent ( x _ 1 , Zoe ) AND think . ccom...",only_seen_as_unacc_subj_as_obj_omitted_transit...
2,The princess teleported a cookie to the goose .,* princess ( x _ 1 ) ; * goose ( x _ 7 ) ; tel...,do_dative_to_pp_dative

Input Distribution:
0
Paula painted a cake in a closet .                                            1
Emma squeezed the cookie .                                                    1
Emma saw a shark .                                                            1
Emma rented a cake on a table beside a computer beside a rock to William .    1
Emma respected that the student teleported the pickle to a girl .             1
Name: count, dtype: int64

Output Distribution:
1
paint . agent ( x _ 1 , Paula ) AND paint . theme ( x _ 1 , x _ 3 ) AND cake ( x _ 3 ) AND cake . nmod . in ( x _ 3 , x _ 6 ) AND closet ( x _ 6 )                                                                                                                                                                                1
* cookie ( x _ 3 ) ; squeeze . agent ( x _ 1 , Emma ) AND squeeze . theme ( x _ 1 , x _ 3 )                                                                                                                                                                                                                                       1
see . agent ( x _ 1 , Emma ) AND see . theme ( x _ 1 , x _ 3 ) AND shark ( x _ 3 )                                                                                                                                                                                                                                                1
rent . agent ( x _ 1 , Emma ) AND rent . theme ( x _ 1 , x _ 3 ) AND rent . recipient ( x _ 1 , William ) AND cake ( x _ 3 ) AND cake . nmod . on ( x _ 3 , x _ 6 ) AND table ( x _ 6 ) AND table . nmod . beside ( x _ 6 , x _ 9 ) AND computer ( x _ 9 ) AND computer . nmod . beside ( x _ 9 , x _ 12 ) AND rock ( x _ 12 )    1
* student ( x _ 4 ) ; * pickle ( x _ 7 ) ; respect . agent ( x _ 1 , Emma ) AND respect . ccomp ( x _ 1 , x _ 5 ) AND teleport . agent ( x _ 5 , x _ 4 ) AND teleport . theme ( x _ 5 , x _ 7 ) AND teleport . recipient ( x _ 5 , x _ 10 ) AND girl ( x _ 10 )                                                                   1
Name: count, dtype: int64

Roles Distribution:
2
prim_to_subj_proper       1000
pp_dative_to_do_dative    1000
subj_to_obj_proper        1000
unacc_to_transitive       1000
active_to_passive         1000
Name: count, dtype: int64

In [5]:
paths = get_dataset_paths("srl")
review_dataset(paths["train"], name=f"SRL - train")

Reviewing SRL - train — (/notebooks/meta-semantic-research/data/srl/train.tsv)
Loaded: SRL - train
Shape: (24155, 3)

,0,1,2
0,A rose was helped by a dog .,"rose ( x _ 1 ) AND help . theme ( x _ 3 , x _ ...","agent(x _ 3 ,x _ 6 ); theme(x _ 3 ,x _ 1 )"
1,The sailor dusted a boy .,"* sailor ( x _ 1 ) ; dust . agent ( x _ 2 , x ...","agent(x _ 2 ,x _ 1 ); theme(x _ 2 ,x _ 4 )"
2,Emma rolled a teacher .,"roll . agent ( x _ 1 , Emma ) AND roll . theme...","agent(x _ 1 ,Emma ); theme(x _ 1 ,x _ 3 )"

Input Distribution:
0
A rose was helped by a dog .                    1
The sandwich was called .                       1
A girl gave Liam the cracker beside a monk .    1
The bird crumpled a strawberry .                1
The raisin was given to Olivia .                1
Name: count, dtype: int64

Output Distribution:
1
rose ( x _ 1 ) AND help . theme ( x _ 3 , x _ 1 ) AND help . agent ( x _ 3 , x _ 6 ) AND dog ( x _ 6 )                                                                                                               1
* sandwich ( x _ 1 ) ; call . theme ( x _ 3 , x _ 1 )                                                                                                                                                                1
* cracker ( x _ 5 ) ; girl ( x _ 1 ) AND give . agent ( x _ 2 , x _ 1 ) AND give . recipient ( x _ 2 , Liam ) AND give . theme ( x _ 2 , x _ 5 ) AND cracker . nmod . beside ( x _ 5 , x _ 8 ) AND monk ( x _ 8 )    1
* bird ( x _ 1 ) ; crumple . agent ( x _ 2 , x _ 1 ) AND crumple . theme ( x _ 2 , x _ 4 ) AND strawberry ( x _ 4 )                                                                                                  1
* raisin ( x _ 1 ) ; give . theme ( x _ 3 , x _ 1 ) AND give . recipient ( x _ 3 , Olivia )                                                                                                                          1
Name: count, dtype: int64

Roles Distribution:
2
agent(x _ 3 ,x _ 6 ); theme(x _ 3 ,x _ 1 )    2001
agent(x _ 2 ,x _ 1 ); theme(x _ 2 ,x _ 4 )    1938
theme(x _ 3 ,x _ 1 )                          1710
agent(x _ 2 ,x _ 1 )                           769
theme(x _ 2 ,x _ 1 )                           678
Name: count, dtype: int64

In [6]:
paths = get_dataset_paths("srt")
review_dataset(paths["train"], name=f"SRT - train")

Reviewing SRT - train — (/notebooks/meta-semantic-research/data/srt/train.tsv)
Loaded: SRT - train
Shape: (24155, 3)

,0,1,2
0,A rose was helped by a dog .,"rose ( x _ 1 ) AND help . theme ( x _ 3 , x _ ...",in_distribution
1,The sailor dusted a boy .,"* sailor ( x _ 1 ) ; dust . agent ( x _ 2 , x ...",in_distribution
2,Emma rolled a teacher .,"roll . agent ( x _ 1 , Emma ) AND roll . theme...",in_distribution

Input Distribution:
0
A rose was helped by a dog .                    1
The sandwich was called .                       1
A girl gave Liam the cracker beside a monk .    1
The bird crumpled a strawberry .                1
The raisin was given to Olivia .                1
Name: count, dtype: int64

Output Distribution:
1
rose ( x _ 1 ) AND help . theme ( x _ 3 , x _ 1 ) AND help . agent ( x _ 3 , x _ 6 ) AND dog ( x _ 6 )                                                                                                               1
* sandwich ( x _ 1 ) ; call . theme ( x _ 3 , x _ 1 )                                                                                                                                                                1
* cracker ( x _ 5 ) ; girl ( x _ 1 ) AND give . agent ( x _ 2 , x _ 1 ) AND give . recipient ( x _ 2 , Liam ) AND give . theme ( x _ 2 , x _ 5 ) AND cracker . nmod . beside ( x _ 5 , x _ 8 ) AND monk ( x _ 8 )    1
* bird ( x _ 1 ) ; crumple . agent ( x _ 2 , x _ 1 ) AND crumple . theme ( x _ 2 , x _ 4 ) AND strawberry ( x _ 4 )                                                                                                  1
* raisin ( x _ 1 ) ; give . theme ( x _ 3 , x _ 1 ) AND give . recipient ( x _ 3 , Olivia )                                                                                                                          1
Name: count, dtype: int64

Roles Distribution:
2
in_distribution                 24000
primitive                         143
exposure_example_unacc_subj         1
exposure_example_unacc              1
exposure_example_subj_common        1
Name: count, dtype: int64

In [7]:
paths = get_dataset_paths("rbm")
review_dataset(paths["train"], name=f"RBM - train")

Reviewing RBM - train — (/notebooks/meta-semantic-research/data/rbm/train.tsv)
Loaded: RBM - train
Shape: (24155, 3)

,0,1,2
0,A rose was helped by a dog .,"rose ( x _ 1 ) AND help . theme ( x _ 3 , x _ ...",in_distribution
1,The sailor dusted a boy .,"* sailor ( x _ 1 ) ; dust . agent ( x _ 2 , x ...",in_distribution
2,Emma rolled a teacher .,"roll . agent ( x _ 1 , Emma ) AND roll . theme...",in_distribution

Input Distribution:
0
A rose was helped by a dog .                    1
The sandwich was called .                       1
A girl gave Liam the cracker beside a monk .    1
The bird crumpled a strawberry .                1
The raisin was given to Olivia .                1
Name: count, dtype: int64

Output Distribution:
1
rose ( x _ 1 ) AND help . theme ( x _ 3 , x _ 1 ) AND help . agent ( x _ 3 , x _ 6 ) AND dog ( x _ 6 )                                                                                                               1
* sandwich ( x _ 1 ) ; call . theme ( x _ 3 , x _ 1 )                                                                                                                                                                1
* cracker ( x _ 5 ) ; girl ( x _ 1 ) AND give . agent ( x _ 2 , x _ 1 ) AND give . recipient ( x _ 2 , Liam ) AND give . theme ( x _ 2 , x _ 5 ) AND cracker . nmod . beside ( x _ 5 , x _ 8 ) AND monk ( x _ 8 )    1
* bird ( x _ 1 ) ; crumple . agent ( x _ 2 , x _ 1 ) AND crumple . theme ( x _ 2 , x _ 4 ) AND strawberry ( x _ 4 )                                                                                                  1
* raisin ( x _ 1 ) ; give . theme ( x _ 3 , x _ 1 ) AND give . recipient ( x _ 3 , Olivia )                                                                                                                          1
Name: count, dtype: int64

Roles Distribution:
2
in_distribution                 24000
primitive                         143
exposure_example_unacc_subj         1
exposure_example_unacc              1
exposure_example_subj_common        1
Name: count, dtype: int64

In [8]:
paths = get_dataset_paths("kga")
review_dataset(paths["train"], name=f"KGA - train")

Reviewing KGA - train — (/notebooks/meta-semantic-research/data/kga/train.tsv)
Loaded: KGA - train
Shape: (24155, 3)

,0,1,2
0,A rose was helped by a dog .,"rose ( x _ 1 ) AND help . theme ( x _ 3 , x _ ...",x _ 1 ) AND help . theme ( x _ 3 -[rose]-> x ...
1,The sailor dusted a boy .,"* sailor ( x _ 1 ) ; dust . agent ( x _ 2 , x ...",x _ 1 ) ; dust . agent ( x _ 2 -[sailor]-> x ...
2,Emma rolled a teacher .,"roll . agent ( x _ 1 , Emma ) AND roll . theme...",x _ 1 -[agent]-> Emma ; x _ 1 -[theme]-> x _ 3

Input Distribution:
0
A rose was helped by a dog .                    1
The sandwich was called .                       1
A girl gave Liam the cracker beside a monk .    1
The bird crumpled a strawberry .                1
The raisin was given to Olivia .                1
Name: count, dtype: int64

Output Distribution:
1
rose ( x _ 1 ) AND help . theme ( x _ 3 , x _ 1 ) AND help . agent ( x _ 3 , x _ 6 ) AND dog ( x _ 6 )                                                                                                               1
* sandwich ( x _ 1 ) ; call . theme ( x _ 3 , x _ 1 )                                                                                                                                                                1
* cracker ( x _ 5 ) ; girl ( x _ 1 ) AND give . agent ( x _ 2 , x _ 1 ) AND give . recipient ( x _ 2 , Liam ) AND give . theme ( x _ 2 , x _ 5 ) AND cracker . nmod . beside ( x _ 5 , x _ 8 ) AND monk ( x _ 8 )    1
* bird ( x _ 1 ) ; crumple . agent ( x _ 2 , x _ 1 ) AND crumple . theme ( x _ 2 , x _ 4 ) AND strawberry ( x _ 4 )                                                                                                  1
* raisin ( x _ 1 ) ; give . theme ( x _ 3 , x _ 1 ) AND give . recipient ( x _ 3 , Olivia )                                                                                                                          1
Name: count, dtype: int64

Roles Distribution:
2
x _ 1  -[agent]-> Emma ; x _ 1  -[theme]-> x _ 3                                  146
x _ 1  -[agent]-> Emma ; x _ 1  -[xcomp]-> x _ 3 ; x _ 3  -[agent]-> Emma         113
x _ 1  -[agent]-> Liam ; x _ 1  -[xcomp]-> x _ 3 ; x _ 3  -[agent]-> Liam          64
x _ 1  -[agent]-> Liam ; x _ 1  -[theme]-> x _ 3                                   55
x _ 1  -[agent]-> Olivia ; x _ 1  -[xcomp]-> x _ 3 ; x _ 3  -[agent]-> Olivia      45
Name: count, dtype: int64